### ISSUE TITLE
Disable Caching

### ISSUE THREAD

**Issue by dbrgn** [SpaceApi-archive/SchemaValidator#6]
Is there a way to tell clients not to use caching at all?

It's a bit annoying that all those apps seem to have several minutes of delay until the actual opening status is updated, even when our SpaceAPI endpoint is updated every 10 seconds.

**Comment by slopjong** [comment]
Does the behaviour change if the cache fied is omitted?

If it doesn't it's the spaceapi consumer (the app) that's caching which is out of our control.

**Comment by dbrgn** [comment]
IIRC when I last tried it was still cached by the API. But I'll do another test to make sure :)

**Comment by dbrgn** [comment]
You're right, when I leave away that key, the directory points directly to the status URL, not to the cached version.

In that case it's probably an issue in the Android app, or just some latency until the updates are mirrored everywhere.
